### ISSUE TITLE
es werden keine daten in die influxdb und mysql db geschrieben

### ISSUE THREAD

**Issue by awiltschek** [Zentris/XaiomiMi-Data-Collector#2]
ich habe alles entsprechend installiert es werden jedoch keine daten in die influxdb und auch nicht in die mysql db geschrieben.
bei influxdb kommt keine meldung es wird jedoch ein measurement angelegt aber keine tags
bei mysql kommt eine meldung dass das man firmware nicht kennt und daher ignoriert aber es werden ebenfalls keine daten geschrieben.
des weiteren ist aus der anleitung nicht ersichtlich in welche der 3 tabellen (ich mutmasse in die sensordaten) überhaupt geschrieben wird.
wozu dienen die anderen beiden tabellen.
wie gesagt dein script liest zwar meine 5 sensoren aber sonst funktioniert es leider nicht.

**Comment by awiltschek** [comment]
**Ergänzung:** 
Unter Python 2.7 funktioniert alles perfekt (mit der Ergänzung dass man firmwareversion und sensorname 
in der DB einbauen muss, da die neuen Sensoren scheinbar neue Tags haben).

**Comment by Zentris** [comment]
@awiltschek Hast du die Daten im Konfigfile entsprechend deiner Umgebung angepasst?
Bitte verwende Python 2.7, ich habe versucht, den Code so zu schreiben, dass er auch mit 3.x läuft, gebe da aber keine Garantie.
Welche Version von MySQL bzw. Influxdb verwendest du?

Aktuell (!!) arbeite ich den gesamten Code um, so dass z.B. die Plausibilität der empfangenen Werte geprüft wird. Weiterhin wird es eine Pufferfunktionalität geben: Wenn die Datenbanken bzw. das WLAN ausfällt, werden die Daten lokal in einer SQLite-DB zwischengespeichert, bis die Verbindung wieder da ist.

**Comment by awiltschek** [comment]
wie gesagt es läuft nun seit gestern bei mir unter 2.7. ich habe noch dein script und das config file um einen sensorname definition erweitert und um das firmware tag welches bei den neuen miflower sensoren ausgelesen werden können. das könntest du in der neuen version schon berücksichtigen

**Comment by Zentris** [comment]
Ok, gut!
Könntest du das bitte als Pull-Request bereitstellen?
Dann arbeite ich das ein.
Ich habe meine Sensoren so ca. 2016/17 gekauft (in ausreichender Menge) so dass ich von ggf. sich ändernden Protokollen nichts merke.

**Comment by awiltschek** [comment]
Werde ich Dir am WE zukommen lassen.

Wie gesagt DB habe ich um Firmware erweitert und ebenfalls im Script eingebaut. Aber das siehst Du dann eh.

Alles Liebe

Alex

 

Von: Zentris <notifications@github.com> 
Gesendet: Sonntag, 10. März 2019 16:59
An: Zentris/XaiomiMi-Data-Collector <XaiomiMi-Data-Collector@noreply.github.com>
Cc: awiltschek <alexander@wiltschek.at>; Mention <mention@noreply.github.com>
Betreff: Re: [Zentris/XaiomiMi-Data-Collector] es werden keine daten in die influxdb und mysql db geschrieben (#2)

 

Ok, gut!
Könntest du das bitte als Pull-Request bereitstellen?
Dann arbeite ich das ein.
Ich habe meine Sensoren so ca. 2016/17 gekauft (in ausreichender Menge) so dass ich von ggf. sich ändernden Protokollen nichts merke.

**Comment by awiltschek** [comment]
Nachdem ich den Pull-Request scheinbar nicht behirne anbei die beiden Files die du brauchst.

Ist nix Hochintellektuelles, da ich kaum Python kann 😊

Lass mich wissen wenn Du was braucht.

Alles Liebe

Alex

 

Von: Zentris <notifications@github.com> 
Gesendet: Sonntag, 10. März 2019 16:59
An: Zentris/XaiomiMi-Data-Collector <XaiomiMi-Data-Collector@noreply.github.com>
Cc: awiltschek <alexander@wiltschek.at>; Mention <mention@noreply.github.com>
Betreff: Re: [Zentris/XaiomiMi-Data-Collector] es werden keine daten in die influxdb und mysql db geschrieben (#2)

 

Ok, gut!
Könntest du das bitte als Pull-Request bereitstellen?
Dann arbeite ich das ein.
Ich habe meine Sensoren so ca. 2016/17 gekauft (in ausreichender Menge) so dass ich von ggf. sich ändernden Protokollen nichts merke.

**Comment by awiltschek** [comment]
Hier noch die SQL Erweiterung



 

Von: Zentris <notifications@github.com> 
Gesendet: Sonntag, 10. März 2019 16:59
An: Zentris/XaiomiMi-Data-Collector <XaiomiMi-Data-Collector@noreply.github.com>
Cc: awiltschek <alexander@wiltschek.at>; Mention <mention@noreply.github.com>
Betreff: Re: [Zentris/XaiomiMi-Data-Collector] es werden keine daten in die influxdb und mysql db geschrieben (#2)

 

Ok, gut!
Könntest du das bitte als Pull-Request bereitstellen?
Dann arbeite ich das ein.
Ich habe meine Sensoren so ca. 2016/17 gekauft (in ausreichender Menge) so dass ich von ggf. sich ändernden Protokollen nichts merke.
